from django.db import IntegrityError
from django.test import TestCase
from django.urls import reverse

from accounts.choices import Role
from accounts.models import User
from audit.choices import AuditAction
from audit.models import AuditLog
from schools.models import School


class SchoolModelTests(TestCase):
    def test_slug_autogenerated_from_name(self):
        school = School.objects.create(name='Green Valley High', code='GVH001')
        self.assertEqual(school.slug, 'green-valley-high')

    def test_code_must_be_unique(self):
        School.objects.create(name='Green Valley High', code='GVH001')
        with self.assertRaises(IntegrityError):
            School.objects.create(name='Other School', code='GVH001')

    def test_deactivation_flag(self):
        school = School.objects.create(name='Green Valley High', code='GVH001')
        self.assertTrue(school.is_active)
        school.is_active = False
        school.save()
        school.refresh_from_db()
        self.assertFalse(school.is_active)


class DashboardViewTests(TestCase):
    def setUp(self):
        self.school_a = School.objects.create(name='Green Valley High', code='GVH001')
        self.admin_a = User.objects.create_user(
            username='admin_a', password='pass1234', role=Role.SCHOOL_ADMIN, school=self.school_a,
        )

    def test_authenticated_school_admin_sees_own_school_name(self):
        self.client.login(username='admin_a', password='pass1234')
        response = self.client.get(reverse('schools:dashboard'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'Green Valley High')

    def test_superuser_redirected_away_from_dashboard(self):
        User.objects.create_superuser(username='root', password='pass1234')
        self.client.login(username='root', password='pass1234')
        response = self.client.get(reverse('schools:dashboard'))
        self.assertRedirects(response, reverse('admin:index'))


class SchoolProfileViewTests(TestCase):
    def setUp(self):
        self.school_a = School.objects.create(name='Green Valley High', code='GVH001')
        self.school_b = School.objects.create(name='Riverside Academy', code='RVA001')
        self.admin_a = User.objects.create_user(
            username='admin_a', password='pass1234', role=Role.SCHOOL_ADMIN, school=self.school_a,
        )
        self.teacher_a = User.objects.create_user(
            username='teacher_a', password='pass1234', role=Role.TEACHER, school=self.school_a,
        )

    def test_teacher_denied_school_profile_access(self):
        self.client.login(username='teacher_a', password='pass1234')
        response = self.client.get(reverse('schools:profile'))
        self.assertEqual(response.status_code, 403)

    def test_school_admin_can_update_only_own_school(self):
        self.client.login(username='admin_a', password='pass1234')
        response = self.client.post(reverse('schools:profile'), {
            'name': 'Green Valley High Updated',
            'address': '',
            'contact_email': '',
            'contact_phone': '',
        })
        self.assertEqual(response.status_code, 302)
        self.school_a.refresh_from_db()
        self.school_b.refresh_from_db()
        self.assertEqual(self.school_a.name, 'Green Valley High Updated')
        self.assertEqual(self.school_b.name, 'Riverside Academy')


class SuperAdminLoginRedirectTests(TestCase):
    def test_superuser_login_redirects_to_django_admin(self):
        User.objects.create_superuser(username='root', password='pass1234')
        response = self.client.post(reverse('accounts:login'), {
            'username': 'root', 'password': 'pass1234',
        })
        self.assertRedirects(response, reverse('admin:index'))


class SuperAdminDashboardViewTests(TestCase):
    def setUp(self):
        self.school_a = School.objects.create(name='Green Valley High', code='GVH001')
        self.school_b = School.objects.create(name='Riverside Academy', code='RVA001', is_active=False)
        User.objects.create_user(username='admin_a', password='pass1234', role=Role.SCHOOL_ADMIN, school=self.school_a)
        User.objects.create_superuser(username='root', password='pass1234')

    def test_superuser_sees_platform_counts(self):
        self.client.login(username='root', password='pass1234')
        response = self.client.get(reverse('schools:super_dashboard'))
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.context['school_count'], 2)
        self.assertEqual(response.context['active_school_count'], 1)

    def test_school_admin_denied_super_dashboard(self):
        self.client.login(username='admin_a', password='pass1234')
        response = self.client.get(reverse('schools:super_dashboard'))
        self.assertEqual(response.status_code, 403)

    def test_anonymous_user_redirected_to_login(self):
        response = self.client.get(reverse('schools:super_dashboard'))
        self.assertEqual(response.status_code, 302)
        self.assertIn(reverse('accounts:login'), response.url)


class SchoolManagementViewTests(TestCase):
    def setUp(self):
        self.school_a = School.objects.create(name='Green Valley High', code='GVH001')
        self.superuser = User.objects.create_superuser(username='root', password='pass1234')
        self.admin_a = User.objects.create_user(
            username='admin_a', password='pass1234', role=Role.SCHOOL_ADMIN, school=self.school_a,
        )
        self.teacher_a = User.objects.create_user(
            username='teacher_a', password='pass1234', role=Role.TEACHER, school=self.school_a,
        )
        self.staff_a = User.objects.create_user(
            username='staff_a', password='pass1234', role=Role.STAFF, school=self.school_a,
        )

    def test_superuser_can_list_schools(self):
        self.client.login(username='root', password='pass1234')
        response = self.client.get(reverse('schools:school_list'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'Green Valley High')

    def test_superuser_can_create_school(self):
        self.client.login(username='root', password='pass1234')
        response = self.client.post(reverse('schools:school_create'), {
            'name': 'New Academy', 'code': 'NEW001', 'address': '', 'contact_email': '', 'contact_phone': '',
        })
        self.assertEqual(response.status_code, 302)
        created = School.objects.get(code='NEW001')
        self.assertEqual(created.name, 'New Academy')

    def test_superuser_can_edit_school(self):
        self.client.login(username='root', password='pass1234')
        response = self.client.post(reverse('schools:school_update', args=[self.school_a.pk]), {
            'name': 'Green Valley High Renamed', 'code': 'GVH001', 'address': '', 'contact_email': '', 'contact_phone': '',
        })
        self.assertEqual(response.status_code, 302)
        self.school_a.refresh_from_db()
        self.assertEqual(self.school_a.name, 'Green Valley High Renamed')

    def test_superuser_can_deactivate_and_reactivate_school(self):
        self.client.login(username='root', password='pass1234')
        response = self.client.post(reverse('schools:school_toggle_active', args=[self.school_a.pk]))
        self.assertEqual(response.status_code, 302)
        self.school_a.refresh_from_db()
        self.assertFalse(self.school_a.is_active)

        response = self.client.post(reverse('schools:school_toggle_active', args=[self.school_a.pk]))
        self.assertEqual(response.status_code, 302)
        self.school_a.refresh_from_db()
        self.assertTrue(self.school_a.is_active)

    def test_create_logs_audit_action(self):
        self.client.login(username='root', password='pass1234')
        self.client.post(reverse('schools:school_create'), {
            'name': 'New Academy', 'code': 'NEW001', 'address': '', 'contact_email': '', 'contact_phone': '',
        })
        created = School.objects.get(code='NEW001')
        self.assertTrue(
            AuditLog.objects.filter(action=AuditAction.CREATE, target_type='School', target_id=str(created.pk)).exists()
        )

    def test_school_admin_denied_school_list(self):
        self.client.login(username='admin_a', password='pass1234')
        response = self.client.get(reverse('schools:school_list'))
        self.assertEqual(response.status_code, 403)

    def test_school_admin_denied_school_create(self):
        self.client.login(username='admin_a', password='pass1234')
        response = self.client.post(reverse('schools:school_create'), {
            'name': 'New Academy', 'code': 'NEW001', 'address': '', 'contact_email': '', 'contact_phone': '',
        })
        self.assertEqual(response.status_code, 403)

    def test_school_admin_denied_school_update(self):
        self.client.login(username='admin_a', password='pass1234')
        response = self.client.get(reverse('schools:school_update', args=[self.school_a.pk]))
        self.assertEqual(response.status_code, 403)

    def test_school_admin_denied_school_toggle_active(self):
        self.client.login(username='admin_a', password='pass1234')
        response = self.client.post(reverse('schools:school_toggle_active', args=[self.school_a.pk]))
        self.assertEqual(response.status_code, 403)

    def test_teacher_denied_school_list(self):
        self.client.login(username='teacher_a', password='pass1234')
        response = self.client.get(reverse('schools:school_list'))
        self.assertEqual(response.status_code, 403)

    def test_staff_denied_school_list(self):
        self.client.login(username='staff_a', password='pass1234')
        response = self.client.get(reverse('schools:school_list'))
        self.assertEqual(response.status_code, 403)
